# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SongWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomWidget(object):
    def setupUi(self, CustomWidget):
        CustomWidget.setObjectName("CustomWidget")
        CustomWidget.resize(792, 130)
        CustomWidget.setMinimumSize(QtCore.QSize(0, 0))
        CustomWidget.setMaximumSize(QtCore.QSize(2560, 130))
        CustomWidget.setStyleSheet("QWidget {\n"
"    background-color: #1d1d1d;\n"
"    color: white;\n"
"    font-family:\"Yandex Sans Display\";\n"
"    font-size: 10pt;\n"
"    margin: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid gray;\n"
"}\n"
"\n"
"QPushButton#pushButton_7:checked {\n"
"    border: 2px solid yellow;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CustomWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/400x400.jfif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(CustomWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(CustomWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(CustomWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(CustomWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(CustomWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/stop_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/play_arrow_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(56, 56))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(CustomWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_3.setMaximumSize(QtCore.QSize(75, 75))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/more_horiz_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(CustomWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_2.setMaximumSize(QtCore.QSize(75, 75))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/close_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CustomWidget)
        QtCore.QMetaObject.connectSlotsByName(CustomWidget)

    def retranslateUi(self, CustomWidget):
        _translate = QtCore.QCoreApplication.translate
        CustomWidget.setWindowTitle(_translate("CustomWidget", "Form"))
        self.label_3.setText(_translate("CustomWidget", "Waiting for Your Love"))
        self.label_4.setText(_translate("CustomWidget", "Outloud"))
        self.label_5.setText(_translate("CustomWidget", "Love Catastrophe"))
        self.label_2.setText(_translate("CustomWidget", "00:00"))
import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomWidget = QtWidgets.QWidget()
    ui = Ui_CustomWidget()
    ui.setupUi(CustomWidget)
    CustomWidget.show()
    sys.exit(app.exec_())
